#coding=utf8

try:
    from . import xspcomm as xsp
except Exception as e:
    import xspcomm as xsp

if __package__ or "." in __name__:
    from .libUT_ICache import *
else:
    from libUT_ICache import *


class DUTICache(object):

    # initialize
    def __init__(self, *args, **kwargs):
        self.dut = DutUnifiedBase(*args)
        self.xclock = xsp.XClock(self.dut.pxcStep, self.dut.pSelf)
        self.xport  = xsp.XPort()
        self.xclock.Add(self.xport)
        self.event = self.xclock.getEvent()
        self.internal_signals = {}
        self.xcfg = xsp.XSignalCFG(self.dut.GetXSignalCFGPath(), self.dut.GetXSignalCFGBasePtr())

        # set output files
        if kwargs.get("waveform_filename"):
            self.dut.SetWaveform(kwargs.get("waveform_filename"))
        if kwargs.get("coverage_filename"):
            self.dut.SetCoverage(kwargs.get("coverage_filename"))

        # all Pins
        self.clock = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.reset = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.auto_ctrlUnitOpt_in_a_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_opcode = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_size = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_source = xsp.XPin(xsp.XData(3, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_address = xsp.XPin(xsp.XData(30, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_mask = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_a_bits_data = xsp.XPin(xsp.XData(64, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_d_ready = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_ctrlUnitOpt_in_d_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.auto_ctrlUnitOpt_in_d_bits_opcode = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.auto_ctrlUnitOpt_in_d_bits_size = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.auto_ctrlUnitOpt_in_d_bits_source = xsp.XPin(xsp.XData(3, xsp.XData.Out), self.event)
        self.auto_ctrlUnitOpt_in_d_bits_data = xsp.XPin(xsp.XData(64, xsp.XData.Out), self.event)
        self.auto_client_out_a_ready = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_client_out_a_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.auto_client_out_a_bits_source = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.auto_client_out_a_bits_address = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.auto_client_out_d_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_opcode = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_size = xsp.XPin(xsp.XData(3, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_source = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_data = xsp.XPin(xsp.XData(256, xsp.XData.In), self.event)
        self.auto_client_out_d_bits_corrupt = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_hartId = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_fetch_req_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_0_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_0_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_1_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_1_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_2_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_2_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_3_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_3_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_4_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_pcMemRead_4_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_2 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_3 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_readValid_4 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_req_bits_backendException = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fetch_resp_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_doubleline = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_vaddr_0 = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_vaddr_1 = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_data = xsp.XPin(xsp.XData(512, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_paddr_0 = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_exception_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_exception_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_pmp_mmio_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_pmp_mmio_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_itlb_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_itlb_pbmt_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_backendException = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_gpaddr = xsp.XPin(xsp.XData(56, xsp.XData.Out), self.event)
        self.io_fetch_resp_bits_isForVSnonLeafPTE = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_topdownIcacheMiss = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_fetch_topdownItlbMiss = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_ftqPrefetch_req_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_ftqPrefetch_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_startAddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_nextlineStart = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_ftqIdx_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_req_bits_ftqIdx_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_bits_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s2_bits_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_bits_flag = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_ftqPrefetch_flushFromBpu_s3_bits_value = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.io_ftqPrefetch_backendException = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_softPrefetch_0_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_0_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_softPrefetch_1_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_1_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_softPrefetch_2_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_softPrefetch_2_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.In), self.event)
        self.io_stop = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_toIFU = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_pmp_0_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_0_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_0_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_1_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_1_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_1_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_2_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_2_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_2_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_3_req_bits_addr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_pmp_3_resp_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_pmp_3_resp_mmio = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_itlb_0_req_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_itlb_0_resp_bits_paddr_0 = xsp.XPin(xsp.XData(48, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_gpaddr_0 = xsp.XPin(xsp.XData(64, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_miss = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_isForVSnonLeafPTE = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_gpf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_pf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_0_resp_bits_excp_0_af_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_req_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_itlb_1_req_bits_vaddr = xsp.XPin(xsp.XData(50, xsp.XData.Out), self.event)
        self.io_itlb_1_resp_bits_paddr_0 = xsp.XPin(xsp.XData(48, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_gpaddr_0 = xsp.XPin(xsp.XData(64, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_miss = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_isForVSnonLeafPTE = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_gpf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_pf_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlb_1_resp_bits_excp_0_af_instr = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_itlbFlushPipe = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_error_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_error_bits_paddr = xsp.XPin(xsp.XData(48, xsp.XData.Out), self.event)
        self.io_error_bits_report_to_beu = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_csr_pf_enable = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_fencei = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_flush = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_perfInfo_only_0_hit = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_only_0_miss = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit_0_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit_0_miss_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_miss_0_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_miss_0_miss_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit_0_except_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_miss_0_except_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_except_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_bank_hit_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_bank_hit_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_perfInfo_hit = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_array = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_all = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_req = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_ack = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_writeen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_be = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_addr = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_indata = xsp.XPin(xsp.XData(148, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_readen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_addr_rd = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_outdata = xsp.XPin(xsp.XData(148, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_1_array = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_all = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_req = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_ack = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_1_writeen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_be = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_addr = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_indata = xsp.XPin(xsp.XData(66, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_readen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_addr_rd = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_1_outdata = xsp.XPin(xsp.XData(66, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_2_array = xsp.XPin(xsp.XData(5, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_all = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_req = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_ack = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_2_writeen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_be = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_addr = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_indata = xsp.XPin(xsp.XData(66, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_readen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_addr_rd = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_2_outdata = xsp.XPin(xsp.XData(66, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_3_array = xsp.XPin(xsp.XData(5, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_all = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_req = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_ack = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_3_writeen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_be = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_addr = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_indata = xsp.XPin(xsp.XData(66, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_readen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_addr_rd = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_3_outdata = xsp.XPin(xsp.XData(66, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_4_array = xsp.XPin(xsp.XData(6, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_all = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_req = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_ack = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.boreChildrenBd_bore_4_writeen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_be = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_addr = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_indata = xsp.XPin(xsp.XData(66, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_readen = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_addr_rd = xsp.XPin(xsp.XData(9, xsp.XData.In), self.event)
        self.boreChildrenBd_bore_4_outdata = xsp.XPin(xsp.XData(66, xsp.XData.Out), self.event)
        self.ICache__metaArray_io_read_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)


        # BindDPI
        self.clock.BindDPIPtr(self.dut.GetDPIHandle("clock", 0), self.dut.GetDPIHandle("clock", 1))
        self.reset.BindDPIPtr(self.dut.GetDPIHandle("reset", 0), self.dut.GetDPIHandle("reset", 1))
        self.auto_ctrlUnitOpt_in_a_ready.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_ready", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_ready", 1))
        self.auto_ctrlUnitOpt_in_a_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_valid", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_valid", 1))
        self.auto_ctrlUnitOpt_in_a_bits_opcode.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_opcode", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_opcode", 1))
        self.auto_ctrlUnitOpt_in_a_bits_size.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_size", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_size", 1))
        self.auto_ctrlUnitOpt_in_a_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_source", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_source", 1))
        self.auto_ctrlUnitOpt_in_a_bits_address.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_address", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_address", 1))
        self.auto_ctrlUnitOpt_in_a_bits_mask.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_mask", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_mask", 1))
        self.auto_ctrlUnitOpt_in_a_bits_data.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_data", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_a_bits_data", 1))
        self.auto_ctrlUnitOpt_in_d_ready.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_ready", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_ready", 1))
        self.auto_ctrlUnitOpt_in_d_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_valid", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_valid", 1))
        self.auto_ctrlUnitOpt_in_d_bits_opcode.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_opcode", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_opcode", 1))
        self.auto_ctrlUnitOpt_in_d_bits_size.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_size", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_size", 1))
        self.auto_ctrlUnitOpt_in_d_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_source", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_source", 1))
        self.auto_ctrlUnitOpt_in_d_bits_data.BindDPIPtr(self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_data", 0), self.dut.GetDPIHandle("auto_ctrlUnitOpt_in_d_bits_data", 1))
        self.auto_client_out_a_ready.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_ready", 0), self.dut.GetDPIHandle("auto_client_out_a_ready", 1))
        self.auto_client_out_a_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_valid", 0), self.dut.GetDPIHandle("auto_client_out_a_valid", 1))
        self.auto_client_out_a_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_bits_source", 0), self.dut.GetDPIHandle("auto_client_out_a_bits_source", 1))
        self.auto_client_out_a_bits_address.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_a_bits_address", 0), self.dut.GetDPIHandle("auto_client_out_a_bits_address", 1))
        self.auto_client_out_d_valid.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_valid", 0), self.dut.GetDPIHandle("auto_client_out_d_valid", 1))
        self.auto_client_out_d_bits_opcode.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_opcode", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_opcode", 1))
        self.auto_client_out_d_bits_size.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_size", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_size", 1))
        self.auto_client_out_d_bits_source.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_source", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_source", 1))
        self.auto_client_out_d_bits_data.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_data", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_data", 1))
        self.auto_client_out_d_bits_corrupt.BindDPIPtr(self.dut.GetDPIHandle("auto_client_out_d_bits_corrupt", 0), self.dut.GetDPIHandle("auto_client_out_d_bits_corrupt", 1))
        self.io_hartId.BindDPIPtr(self.dut.GetDPIHandle("io_hartId", 0), self.dut.GetDPIHandle("io_hartId", 1))
        self.io_fetch_req_ready.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_ready", 0), self.dut.GetDPIHandle("io_fetch_req_ready", 1))
        self.io_fetch_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_valid", 0), self.dut.GetDPIHandle("io_fetch_req_valid", 1))
        self.io_fetch_req_bits_pcMemRead_0_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_0_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_0_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_1_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_1_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_1_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_2_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_2_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_2_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_3_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_3_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_3_nextlineStart", 1))
        self.io_fetch_req_bits_pcMemRead_4_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_startAddr", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_startAddr", 1))
        self.io_fetch_req_bits_pcMemRead_4_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_nextlineStart", 0), self.dut.GetDPIHandle("io_fetch_req_bits_pcMemRead_4_nextlineStart", 1))
        self.io_fetch_req_bits_readValid_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_0", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_0", 1))
        self.io_fetch_req_bits_readValid_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_1", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_1", 1))
        self.io_fetch_req_bits_readValid_2.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_2", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_2", 1))
        self.io_fetch_req_bits_readValid_3.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_3", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_3", 1))
        self.io_fetch_req_bits_readValid_4.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_readValid_4", 0), self.dut.GetDPIHandle("io_fetch_req_bits_readValid_4", 1))
        self.io_fetch_req_bits_backendException.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_req_bits_backendException", 0), self.dut.GetDPIHandle("io_fetch_req_bits_backendException", 1))
        self.io_fetch_resp_valid.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_valid", 0), self.dut.GetDPIHandle("io_fetch_resp_valid", 1))
        self.io_fetch_resp_bits_doubleline.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_doubleline", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_doubleline", 1))
        self.io_fetch_resp_bits_vaddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_vaddr_0", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_vaddr_0", 1))
        self.io_fetch_resp_bits_vaddr_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_vaddr_1", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_vaddr_1", 1))
        self.io_fetch_resp_bits_data.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_data", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_data", 1))
        self.io_fetch_resp_bits_paddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_paddr_0", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_paddr_0", 1))
        self.io_fetch_resp_bits_exception_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_exception_0", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_exception_0", 1))
        self.io_fetch_resp_bits_exception_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_exception_1", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_exception_1", 1))
        self.io_fetch_resp_bits_pmp_mmio_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_pmp_mmio_0", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_pmp_mmio_0", 1))
        self.io_fetch_resp_bits_pmp_mmio_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_pmp_mmio_1", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_pmp_mmio_1", 1))
        self.io_fetch_resp_bits_itlb_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_itlb_pbmt_0", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_itlb_pbmt_0", 1))
        self.io_fetch_resp_bits_itlb_pbmt_1.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_itlb_pbmt_1", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_itlb_pbmt_1", 1))
        self.io_fetch_resp_bits_backendException.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_backendException", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_backendException", 1))
        self.io_fetch_resp_bits_gpaddr.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_gpaddr", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_gpaddr", 1))
        self.io_fetch_resp_bits_isForVSnonLeafPTE.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_resp_bits_isForVSnonLeafPTE", 0), self.dut.GetDPIHandle("io_fetch_resp_bits_isForVSnonLeafPTE", 1))
        self.io_fetch_topdownIcacheMiss.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_topdownIcacheMiss", 0), self.dut.GetDPIHandle("io_fetch_topdownIcacheMiss", 1))
        self.io_fetch_topdownItlbMiss.BindDPIPtr(self.dut.GetDPIHandle("io_fetch_topdownItlbMiss", 0), self.dut.GetDPIHandle("io_fetch_topdownItlbMiss", 1))
        self.io_ftqPrefetch_req_ready.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_ready", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_ready", 1))
        self.io_ftqPrefetch_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_valid", 1))
        self.io_ftqPrefetch_req_bits_startAddr.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_startAddr", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_startAddr", 1))
        self.io_ftqPrefetch_req_bits_nextlineStart.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_nextlineStart", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_nextlineStart", 1))
        self.io_ftqPrefetch_req_bits_ftqIdx_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_flag", 1))
        self.io_ftqPrefetch_req_bits_ftqIdx_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_req_bits_ftqIdx_value", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_valid", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_bits_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_flag", 1))
        self.io_ftqPrefetch_flushFromBpu_s2_bits_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s2_bits_value", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_valid.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_valid", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_valid", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_bits_flag.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_flag", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_flag", 1))
        self.io_ftqPrefetch_flushFromBpu_s3_bits_value.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_value", 0), self.dut.GetDPIHandle("io_ftqPrefetch_flushFromBpu_s3_bits_value", 1))
        self.io_ftqPrefetch_backendException.BindDPIPtr(self.dut.GetDPIHandle("io_ftqPrefetch_backendException", 0), self.dut.GetDPIHandle("io_ftqPrefetch_backendException", 1))
        self.io_softPrefetch_0_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_0_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_0_valid", 1))
        self.io_softPrefetch_0_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_0_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_0_bits_vaddr", 1))
        self.io_softPrefetch_1_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_1_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_1_valid", 1))
        self.io_softPrefetch_1_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_1_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_1_bits_vaddr", 1))
        self.io_softPrefetch_2_valid.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_2_valid", 0), self.dut.GetDPIHandle("io_softPrefetch_2_valid", 1))
        self.io_softPrefetch_2_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_softPrefetch_2_bits_vaddr", 0), self.dut.GetDPIHandle("io_softPrefetch_2_bits_vaddr", 1))
        self.io_stop.BindDPIPtr(self.dut.GetDPIHandle("io_stop", 0), self.dut.GetDPIHandle("io_stop", 1))
        self.io_toIFU.BindDPIPtr(self.dut.GetDPIHandle("io_toIFU", 0), self.dut.GetDPIHandle("io_toIFU", 1))
        self.io_pmp_0_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_0_req_bits_addr", 1))
        self.io_pmp_0_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_0_resp_instr", 1))
        self.io_pmp_0_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_0_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_0_resp_mmio", 1))
        self.io_pmp_1_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_1_req_bits_addr", 1))
        self.io_pmp_1_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_1_resp_instr", 1))
        self.io_pmp_1_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_1_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_1_resp_mmio", 1))
        self.io_pmp_2_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_2_req_bits_addr", 1))
        self.io_pmp_2_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_2_resp_instr", 1))
        self.io_pmp_2_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_2_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_2_resp_mmio", 1))
        self.io_pmp_3_req_bits_addr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_req_bits_addr", 0), self.dut.GetDPIHandle("io_pmp_3_req_bits_addr", 1))
        self.io_pmp_3_resp_instr.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_resp_instr", 0), self.dut.GetDPIHandle("io_pmp_3_resp_instr", 1))
        self.io_pmp_3_resp_mmio.BindDPIPtr(self.dut.GetDPIHandle("io_pmp_3_resp_mmio", 0), self.dut.GetDPIHandle("io_pmp_3_resp_mmio", 1))
        self.io_itlb_0_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_req_valid", 0), self.dut.GetDPIHandle("io_itlb_0_req_valid", 1))
        self.io_itlb_0_req_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_req_bits_vaddr", 0), self.dut.GetDPIHandle("io_itlb_0_req_bits_vaddr", 1))
        self.io_itlb_0_resp_bits_paddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_paddr_0", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_paddr_0", 1))
        self.io_itlb_0_resp_bits_gpaddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_gpaddr_0", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_gpaddr_0", 1))
        self.io_itlb_0_resp_bits_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_pbmt_0", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_pbmt_0", 1))
        self.io_itlb_0_resp_bits_miss.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_miss", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_miss", 1))
        self.io_itlb_0_resp_bits_isForVSnonLeafPTE.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_isForVSnonLeafPTE", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_isForVSnonLeafPTE", 1))
        self.io_itlb_0_resp_bits_excp_0_gpf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_gpf_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_gpf_instr", 1))
        self.io_itlb_0_resp_bits_excp_0_pf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_pf_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_pf_instr", 1))
        self.io_itlb_0_resp_bits_excp_0_af_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_af_instr", 0), self.dut.GetDPIHandle("io_itlb_0_resp_bits_excp_0_af_instr", 1))
        self.io_itlb_1_req_valid.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_req_valid", 0), self.dut.GetDPIHandle("io_itlb_1_req_valid", 1))
        self.io_itlb_1_req_bits_vaddr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_req_bits_vaddr", 0), self.dut.GetDPIHandle("io_itlb_1_req_bits_vaddr", 1))
        self.io_itlb_1_resp_bits_paddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_paddr_0", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_paddr_0", 1))
        self.io_itlb_1_resp_bits_gpaddr_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_gpaddr_0", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_gpaddr_0", 1))
        self.io_itlb_1_resp_bits_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_pbmt_0", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_pbmt_0", 1))
        self.io_itlb_1_resp_bits_miss.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_miss", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_miss", 1))
        self.io_itlb_1_resp_bits_isForVSnonLeafPTE.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_isForVSnonLeafPTE", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_isForVSnonLeafPTE", 1))
        self.io_itlb_1_resp_bits_excp_0_gpf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_gpf_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_gpf_instr", 1))
        self.io_itlb_1_resp_bits_excp_0_pf_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_pf_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_pf_instr", 1))
        self.io_itlb_1_resp_bits_excp_0_af_instr.BindDPIPtr(self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_af_instr", 0), self.dut.GetDPIHandle("io_itlb_1_resp_bits_excp_0_af_instr", 1))
        self.io_itlbFlushPipe.BindDPIPtr(self.dut.GetDPIHandle("io_itlbFlushPipe", 0), self.dut.GetDPIHandle("io_itlbFlushPipe", 1))
        self.io_error_valid.BindDPIPtr(self.dut.GetDPIHandle("io_error_valid", 0), self.dut.GetDPIHandle("io_error_valid", 1))
        self.io_error_bits_paddr.BindDPIPtr(self.dut.GetDPIHandle("io_error_bits_paddr", 0), self.dut.GetDPIHandle("io_error_bits_paddr", 1))
        self.io_error_bits_report_to_beu.BindDPIPtr(self.dut.GetDPIHandle("io_error_bits_report_to_beu", 0), self.dut.GetDPIHandle("io_error_bits_report_to_beu", 1))
        self.io_csr_pf_enable.BindDPIPtr(self.dut.GetDPIHandle("io_csr_pf_enable", 0), self.dut.GetDPIHandle("io_csr_pf_enable", 1))
        self.io_fencei.BindDPIPtr(self.dut.GetDPIHandle("io_fencei", 0), self.dut.GetDPIHandle("io_fencei", 1))
        self.io_flush.BindDPIPtr(self.dut.GetDPIHandle("io_flush", 0), self.dut.GetDPIHandle("io_flush", 1))
        self.io_perfInfo_only_0_hit.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_only_0_hit", 0), self.dut.GetDPIHandle("io_perfInfo_only_0_hit", 1))
        self.io_perfInfo_only_0_miss.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_only_0_miss", 0), self.dut.GetDPIHandle("io_perfInfo_only_0_miss", 1))
        self.io_perfInfo_hit_0_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit_0_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_hit_0_hit_1", 1))
        self.io_perfInfo_hit_0_miss_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit_0_miss_1", 0), self.dut.GetDPIHandle("io_perfInfo_hit_0_miss_1", 1))
        self.io_perfInfo_miss_0_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_miss_0_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_miss_0_hit_1", 1))
        self.io_perfInfo_miss_0_miss_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_miss_0_miss_1", 0), self.dut.GetDPIHandle("io_perfInfo_miss_0_miss_1", 1))
        self.io_perfInfo_hit_0_except_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit_0_except_1", 0), self.dut.GetDPIHandle("io_perfInfo_hit_0_except_1", 1))
        self.io_perfInfo_miss_0_except_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_miss_0_except_1", 0), self.dut.GetDPIHandle("io_perfInfo_miss_0_except_1", 1))
        self.io_perfInfo_except_0.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_except_0", 0), self.dut.GetDPIHandle("io_perfInfo_except_0", 1))
        self.io_perfInfo_bank_hit_0.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_bank_hit_0", 0), self.dut.GetDPIHandle("io_perfInfo_bank_hit_0", 1))
        self.io_perfInfo_bank_hit_1.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_bank_hit_1", 0), self.dut.GetDPIHandle("io_perfInfo_bank_hit_1", 1))
        self.io_perfInfo_hit.BindDPIPtr(self.dut.GetDPIHandle("io_perfInfo_hit", 0), self.dut.GetDPIHandle("io_perfInfo_hit", 1))
        self.boreChildrenBd_bore_array.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_array", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_array", 1))
        self.boreChildrenBd_bore_all.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_all", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_all", 1))
        self.boreChildrenBd_bore_req.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_req", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_req", 1))
        self.boreChildrenBd_bore_ack.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_ack", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_ack", 1))
        self.boreChildrenBd_bore_writeen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_writeen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_writeen", 1))
        self.boreChildrenBd_bore_be.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_be", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_be", 1))
        self.boreChildrenBd_bore_addr.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_addr", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_addr", 1))
        self.boreChildrenBd_bore_indata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_indata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_indata", 1))
        self.boreChildrenBd_bore_readen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_readen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_readen", 1))
        self.boreChildrenBd_bore_addr_rd.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_addr_rd", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_addr_rd", 1))
        self.boreChildrenBd_bore_outdata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_outdata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_outdata", 1))
        self.boreChildrenBd_bore_1_array.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_array", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_array", 1))
        self.boreChildrenBd_bore_1_all.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_all", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_all", 1))
        self.boreChildrenBd_bore_1_req.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_req", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_req", 1))
        self.boreChildrenBd_bore_1_ack.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_ack", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_ack", 1))
        self.boreChildrenBd_bore_1_writeen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_writeen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_writeen", 1))
        self.boreChildrenBd_bore_1_be.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_be", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_be", 1))
        self.boreChildrenBd_bore_1_addr.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_addr", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_addr", 1))
        self.boreChildrenBd_bore_1_indata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_indata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_indata", 1))
        self.boreChildrenBd_bore_1_readen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_readen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_readen", 1))
        self.boreChildrenBd_bore_1_addr_rd.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_addr_rd", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_addr_rd", 1))
        self.boreChildrenBd_bore_1_outdata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_1_outdata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_1_outdata", 1))
        self.boreChildrenBd_bore_2_array.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_array", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_array", 1))
        self.boreChildrenBd_bore_2_all.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_all", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_all", 1))
        self.boreChildrenBd_bore_2_req.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_req", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_req", 1))
        self.boreChildrenBd_bore_2_ack.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_ack", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_ack", 1))
        self.boreChildrenBd_bore_2_writeen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_writeen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_writeen", 1))
        self.boreChildrenBd_bore_2_be.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_be", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_be", 1))
        self.boreChildrenBd_bore_2_addr.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_addr", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_addr", 1))
        self.boreChildrenBd_bore_2_indata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_indata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_indata", 1))
        self.boreChildrenBd_bore_2_readen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_readen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_readen", 1))
        self.boreChildrenBd_bore_2_addr_rd.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_addr_rd", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_addr_rd", 1))
        self.boreChildrenBd_bore_2_outdata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_2_outdata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_2_outdata", 1))
        self.boreChildrenBd_bore_3_array.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_array", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_array", 1))
        self.boreChildrenBd_bore_3_all.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_all", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_all", 1))
        self.boreChildrenBd_bore_3_req.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_req", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_req", 1))
        self.boreChildrenBd_bore_3_ack.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_ack", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_ack", 1))
        self.boreChildrenBd_bore_3_writeen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_writeen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_writeen", 1))
        self.boreChildrenBd_bore_3_be.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_be", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_be", 1))
        self.boreChildrenBd_bore_3_addr.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_addr", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_addr", 1))
        self.boreChildrenBd_bore_3_indata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_indata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_indata", 1))
        self.boreChildrenBd_bore_3_readen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_readen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_readen", 1))
        self.boreChildrenBd_bore_3_addr_rd.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_addr_rd", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_addr_rd", 1))
        self.boreChildrenBd_bore_3_outdata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_3_outdata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_3_outdata", 1))
        self.boreChildrenBd_bore_4_array.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_array", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_array", 1))
        self.boreChildrenBd_bore_4_all.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_all", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_all", 1))
        self.boreChildrenBd_bore_4_req.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_req", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_req", 1))
        self.boreChildrenBd_bore_4_ack.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_ack", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_ack", 1))
        self.boreChildrenBd_bore_4_writeen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_writeen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_writeen", 1))
        self.boreChildrenBd_bore_4_be.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_be", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_be", 1))
        self.boreChildrenBd_bore_4_addr.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_addr", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_addr", 1))
        self.boreChildrenBd_bore_4_indata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_indata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_indata", 1))
        self.boreChildrenBd_bore_4_readen.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_readen", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_readen", 1))
        self.boreChildrenBd_bore_4_addr_rd.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_addr_rd", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_addr_rd", 1))
        self.boreChildrenBd_bore_4_outdata.BindDPIPtr(self.dut.GetDPIHandle("boreChildrenBd_bore_4_outdata", 0), self.dut.GetDPIHandle("boreChildrenBd_bore_4_outdata", 1))
        self.ICache__metaArray_io_read_ready.BindDPIPtr(self.dut.GetDPIHandle("ICache__metaArray_io_read_ready", 0), self.dut.GetDPIHandle("ICache__metaArray_io_read_ready", 1))


        # Add2Port
        self.xport.Add("clock", self.clock.xdata)
        self.xport.Add("reset", self.reset.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_ready", self.auto_ctrlUnitOpt_in_a_ready.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_valid", self.auto_ctrlUnitOpt_in_a_valid.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_opcode", self.auto_ctrlUnitOpt_in_a_bits_opcode.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_size", self.auto_ctrlUnitOpt_in_a_bits_size.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_source", self.auto_ctrlUnitOpt_in_a_bits_source.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_address", self.auto_ctrlUnitOpt_in_a_bits_address.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_mask", self.auto_ctrlUnitOpt_in_a_bits_mask.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_a_bits_data", self.auto_ctrlUnitOpt_in_a_bits_data.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_ready", self.auto_ctrlUnitOpt_in_d_ready.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_valid", self.auto_ctrlUnitOpt_in_d_valid.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_bits_opcode", self.auto_ctrlUnitOpt_in_d_bits_opcode.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_bits_size", self.auto_ctrlUnitOpt_in_d_bits_size.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_bits_source", self.auto_ctrlUnitOpt_in_d_bits_source.xdata)
        self.xport.Add("auto_ctrlUnitOpt_in_d_bits_data", self.auto_ctrlUnitOpt_in_d_bits_data.xdata)
        self.xport.Add("auto_client_out_a_ready", self.auto_client_out_a_ready.xdata)
        self.xport.Add("auto_client_out_a_valid", self.auto_client_out_a_valid.xdata)
        self.xport.Add("auto_client_out_a_bits_source", self.auto_client_out_a_bits_source.xdata)
        self.xport.Add("auto_client_out_a_bits_address", self.auto_client_out_a_bits_address.xdata)
        self.xport.Add("auto_client_out_d_valid", self.auto_client_out_d_valid.xdata)
        self.xport.Add("auto_client_out_d_bits_opcode", self.auto_client_out_d_bits_opcode.xdata)
        self.xport.Add("auto_client_out_d_bits_size", self.auto_client_out_d_bits_size.xdata)
        self.xport.Add("auto_client_out_d_bits_source", self.auto_client_out_d_bits_source.xdata)
        self.xport.Add("auto_client_out_d_bits_data", self.auto_client_out_d_bits_data.xdata)
        self.xport.Add("auto_client_out_d_bits_corrupt", self.auto_client_out_d_bits_corrupt.xdata)
        self.xport.Add("io_hartId", self.io_hartId.xdata)
        self.xport.Add("io_fetch_req_ready", self.io_fetch_req_ready.xdata)
        self.xport.Add("io_fetch_req_valid", self.io_fetch_req_valid.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_0_startAddr", self.io_fetch_req_bits_pcMemRead_0_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_0_nextlineStart", self.io_fetch_req_bits_pcMemRead_0_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_1_startAddr", self.io_fetch_req_bits_pcMemRead_1_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_1_nextlineStart", self.io_fetch_req_bits_pcMemRead_1_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_2_startAddr", self.io_fetch_req_bits_pcMemRead_2_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_2_nextlineStart", self.io_fetch_req_bits_pcMemRead_2_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_3_startAddr", self.io_fetch_req_bits_pcMemRead_3_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_3_nextlineStart", self.io_fetch_req_bits_pcMemRead_3_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_4_startAddr", self.io_fetch_req_bits_pcMemRead_4_startAddr.xdata)
        self.xport.Add("io_fetch_req_bits_pcMemRead_4_nextlineStart", self.io_fetch_req_bits_pcMemRead_4_nextlineStart.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_0", self.io_fetch_req_bits_readValid_0.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_1", self.io_fetch_req_bits_readValid_1.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_2", self.io_fetch_req_bits_readValid_2.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_3", self.io_fetch_req_bits_readValid_3.xdata)
        self.xport.Add("io_fetch_req_bits_readValid_4", self.io_fetch_req_bits_readValid_4.xdata)
        self.xport.Add("io_fetch_req_bits_backendException", self.io_fetch_req_bits_backendException.xdata)
        self.xport.Add("io_fetch_resp_valid", self.io_fetch_resp_valid.xdata)
        self.xport.Add("io_fetch_resp_bits_doubleline", self.io_fetch_resp_bits_doubleline.xdata)
        self.xport.Add("io_fetch_resp_bits_vaddr_0", self.io_fetch_resp_bits_vaddr_0.xdata)
        self.xport.Add("io_fetch_resp_bits_vaddr_1", self.io_fetch_resp_bits_vaddr_1.xdata)
        self.xport.Add("io_fetch_resp_bits_data", self.io_fetch_resp_bits_data.xdata)
        self.xport.Add("io_fetch_resp_bits_paddr_0", self.io_fetch_resp_bits_paddr_0.xdata)
        self.xport.Add("io_fetch_resp_bits_exception_0", self.io_fetch_resp_bits_exception_0.xdata)
        self.xport.Add("io_fetch_resp_bits_exception_1", self.io_fetch_resp_bits_exception_1.xdata)
        self.xport.Add("io_fetch_resp_bits_pmp_mmio_0", self.io_fetch_resp_bits_pmp_mmio_0.xdata)
        self.xport.Add("io_fetch_resp_bits_pmp_mmio_1", self.io_fetch_resp_bits_pmp_mmio_1.xdata)
        self.xport.Add("io_fetch_resp_bits_itlb_pbmt_0", self.io_fetch_resp_bits_itlb_pbmt_0.xdata)
        self.xport.Add("io_fetch_resp_bits_itlb_pbmt_1", self.io_fetch_resp_bits_itlb_pbmt_1.xdata)
        self.xport.Add("io_fetch_resp_bits_backendException", self.io_fetch_resp_bits_backendException.xdata)
        self.xport.Add("io_fetch_resp_bits_gpaddr", self.io_fetch_resp_bits_gpaddr.xdata)
        self.xport.Add("io_fetch_resp_bits_isForVSnonLeafPTE", self.io_fetch_resp_bits_isForVSnonLeafPTE.xdata)
        self.xport.Add("io_fetch_topdownIcacheMiss", self.io_fetch_topdownIcacheMiss.xdata)
        self.xport.Add("io_fetch_topdownItlbMiss", self.io_fetch_topdownItlbMiss.xdata)
        self.xport.Add("io_ftqPrefetch_req_ready", self.io_ftqPrefetch_req_ready.xdata)
        self.xport.Add("io_ftqPrefetch_req_valid", self.io_ftqPrefetch_req_valid.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_startAddr", self.io_ftqPrefetch_req_bits_startAddr.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_nextlineStart", self.io_ftqPrefetch_req_bits_nextlineStart.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_ftqIdx_flag", self.io_ftqPrefetch_req_bits_ftqIdx_flag.xdata)
        self.xport.Add("io_ftqPrefetch_req_bits_ftqIdx_value", self.io_ftqPrefetch_req_bits_ftqIdx_value.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_valid", self.io_ftqPrefetch_flushFromBpu_s2_valid.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_bits_flag", self.io_ftqPrefetch_flushFromBpu_s2_bits_flag.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s2_bits_value", self.io_ftqPrefetch_flushFromBpu_s2_bits_value.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_valid", self.io_ftqPrefetch_flushFromBpu_s3_valid.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_bits_flag", self.io_ftqPrefetch_flushFromBpu_s3_bits_flag.xdata)
        self.xport.Add("io_ftqPrefetch_flushFromBpu_s3_bits_value", self.io_ftqPrefetch_flushFromBpu_s3_bits_value.xdata)
        self.xport.Add("io_ftqPrefetch_backendException", self.io_ftqPrefetch_backendException.xdata)
        self.xport.Add("io_softPrefetch_0_valid", self.io_softPrefetch_0_valid.xdata)
        self.xport.Add("io_softPrefetch_0_bits_vaddr", self.io_softPrefetch_0_bits_vaddr.xdata)
        self.xport.Add("io_softPrefetch_1_valid", self.io_softPrefetch_1_valid.xdata)
        self.xport.Add("io_softPrefetch_1_bits_vaddr", self.io_softPrefetch_1_bits_vaddr.xdata)
        self.xport.Add("io_softPrefetch_2_valid", self.io_softPrefetch_2_valid.xdata)
        self.xport.Add("io_softPrefetch_2_bits_vaddr", self.io_softPrefetch_2_bits_vaddr.xdata)
        self.xport.Add("io_stop", self.io_stop.xdata)
        self.xport.Add("io_toIFU", self.io_toIFU.xdata)
        self.xport.Add("io_pmp_0_req_bits_addr", self.io_pmp_0_req_bits_addr.xdata)
        self.xport.Add("io_pmp_0_resp_instr", self.io_pmp_0_resp_instr.xdata)
        self.xport.Add("io_pmp_0_resp_mmio", self.io_pmp_0_resp_mmio.xdata)
        self.xport.Add("io_pmp_1_req_bits_addr", self.io_pmp_1_req_bits_addr.xdata)
        self.xport.Add("io_pmp_1_resp_instr", self.io_pmp_1_resp_instr.xdata)
        self.xport.Add("io_pmp_1_resp_mmio", self.io_pmp_1_resp_mmio.xdata)
        self.xport.Add("io_pmp_2_req_bits_addr", self.io_pmp_2_req_bits_addr.xdata)
        self.xport.Add("io_pmp_2_resp_instr", self.io_pmp_2_resp_instr.xdata)
        self.xport.Add("io_pmp_2_resp_mmio", self.io_pmp_2_resp_mmio.xdata)
        self.xport.Add("io_pmp_3_req_bits_addr", self.io_pmp_3_req_bits_addr.xdata)
        self.xport.Add("io_pmp_3_resp_instr", self.io_pmp_3_resp_instr.xdata)
        self.xport.Add("io_pmp_3_resp_mmio", self.io_pmp_3_resp_mmio.xdata)
        self.xport.Add("io_itlb_0_req_valid", self.io_itlb_0_req_valid.xdata)
        self.xport.Add("io_itlb_0_req_bits_vaddr", self.io_itlb_0_req_bits_vaddr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_paddr_0", self.io_itlb_0_resp_bits_paddr_0.xdata)
        self.xport.Add("io_itlb_0_resp_bits_gpaddr_0", self.io_itlb_0_resp_bits_gpaddr_0.xdata)
        self.xport.Add("io_itlb_0_resp_bits_pbmt_0", self.io_itlb_0_resp_bits_pbmt_0.xdata)
        self.xport.Add("io_itlb_0_resp_bits_miss", self.io_itlb_0_resp_bits_miss.xdata)
        self.xport.Add("io_itlb_0_resp_bits_isForVSnonLeafPTE", self.io_itlb_0_resp_bits_isForVSnonLeafPTE.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_gpf_instr", self.io_itlb_0_resp_bits_excp_0_gpf_instr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_pf_instr", self.io_itlb_0_resp_bits_excp_0_pf_instr.xdata)
        self.xport.Add("io_itlb_0_resp_bits_excp_0_af_instr", self.io_itlb_0_resp_bits_excp_0_af_instr.xdata)
        self.xport.Add("io_itlb_1_req_valid", self.io_itlb_1_req_valid.xdata)
        self.xport.Add("io_itlb_1_req_bits_vaddr", self.io_itlb_1_req_bits_vaddr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_paddr_0", self.io_itlb_1_resp_bits_paddr_0.xdata)
        self.xport.Add("io_itlb_1_resp_bits_gpaddr_0", self.io_itlb_1_resp_bits_gpaddr_0.xdata)
        self.xport.Add("io_itlb_1_resp_bits_pbmt_0", self.io_itlb_1_resp_bits_pbmt_0.xdata)
        self.xport.Add("io_itlb_1_resp_bits_miss", self.io_itlb_1_resp_bits_miss.xdata)
        self.xport.Add("io_itlb_1_resp_bits_isForVSnonLeafPTE", self.io_itlb_1_resp_bits_isForVSnonLeafPTE.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_gpf_instr", self.io_itlb_1_resp_bits_excp_0_gpf_instr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_pf_instr", self.io_itlb_1_resp_bits_excp_0_pf_instr.xdata)
        self.xport.Add("io_itlb_1_resp_bits_excp_0_af_instr", self.io_itlb_1_resp_bits_excp_0_af_instr.xdata)
        self.xport.Add("io_itlbFlushPipe", self.io_itlbFlushPipe.xdata)
        self.xport.Add("io_error_valid", self.io_error_valid.xdata)
        self.xport.Add("io_error_bits_paddr", self.io_error_bits_paddr.xdata)
        self.xport.Add("io_error_bits_report_to_beu", self.io_error_bits_report_to_beu.xdata)
        self.xport.Add("io_csr_pf_enable", self.io_csr_pf_enable.xdata)
        self.xport.Add("io_fencei", self.io_fencei.xdata)
        self.xport.Add("io_flush", self.io_flush.xdata)
        self.xport.Add("io_perfInfo_only_0_hit", self.io_perfInfo_only_0_hit.xdata)
        self.xport.Add("io_perfInfo_only_0_miss", self.io_perfInfo_only_0_miss.xdata)
        self.xport.Add("io_perfInfo_hit_0_hit_1", self.io_perfInfo_hit_0_hit_1.xdata)
        self.xport.Add("io_perfInfo_hit_0_miss_1", self.io_perfInfo_hit_0_miss_1.xdata)
        self.xport.Add("io_perfInfo_miss_0_hit_1", self.io_perfInfo_miss_0_hit_1.xdata)
        self.xport.Add("io_perfInfo_miss_0_miss_1", self.io_perfInfo_miss_0_miss_1.xdata)
        self.xport.Add("io_perfInfo_hit_0_except_1", self.io_perfInfo_hit_0_except_1.xdata)
        self.xport.Add("io_perfInfo_miss_0_except_1", self.io_perfInfo_miss_0_except_1.xdata)
        self.xport.Add("io_perfInfo_except_0", self.io_perfInfo_except_0.xdata)
        self.xport.Add("io_perfInfo_bank_hit_0", self.io_perfInfo_bank_hit_0.xdata)
        self.xport.Add("io_perfInfo_bank_hit_1", self.io_perfInfo_bank_hit_1.xdata)
        self.xport.Add("io_perfInfo_hit", self.io_perfInfo_hit.xdata)
        self.xport.Add("boreChildrenBd_bore_array", self.boreChildrenBd_bore_array.xdata)
        self.xport.Add("boreChildrenBd_bore_all", self.boreChildrenBd_bore_all.xdata)
        self.xport.Add("boreChildrenBd_bore_req", self.boreChildrenBd_bore_req.xdata)
        self.xport.Add("boreChildrenBd_bore_ack", self.boreChildrenBd_bore_ack.xdata)
        self.xport.Add("boreChildrenBd_bore_writeen", self.boreChildrenBd_bore_writeen.xdata)
        self.xport.Add("boreChildrenBd_bore_be", self.boreChildrenBd_bore_be.xdata)
        self.xport.Add("boreChildrenBd_bore_addr", self.boreChildrenBd_bore_addr.xdata)
        self.xport.Add("boreChildrenBd_bore_indata", self.boreChildrenBd_bore_indata.xdata)
        self.xport.Add("boreChildrenBd_bore_readen", self.boreChildrenBd_bore_readen.xdata)
        self.xport.Add("boreChildrenBd_bore_addr_rd", self.boreChildrenBd_bore_addr_rd.xdata)
        self.xport.Add("boreChildrenBd_bore_outdata", self.boreChildrenBd_bore_outdata.xdata)
        self.xport.Add("boreChildrenBd_bore_1_array", self.boreChildrenBd_bore_1_array.xdata)
        self.xport.Add("boreChildrenBd_bore_1_all", self.boreChildrenBd_bore_1_all.xdata)
        self.xport.Add("boreChildrenBd_bore_1_req", self.boreChildrenBd_bore_1_req.xdata)
        self.xport.Add("boreChildrenBd_bore_1_ack", self.boreChildrenBd_bore_1_ack.xdata)
        self.xport.Add("boreChildrenBd_bore_1_writeen", self.boreChildrenBd_bore_1_writeen.xdata)
        self.xport.Add("boreChildrenBd_bore_1_be", self.boreChildrenBd_bore_1_be.xdata)
        self.xport.Add("boreChildrenBd_bore_1_addr", self.boreChildrenBd_bore_1_addr.xdata)
        self.xport.Add("boreChildrenBd_bore_1_indata", self.boreChildrenBd_bore_1_indata.xdata)
        self.xport.Add("boreChildrenBd_bore_1_readen", self.boreChildrenBd_bore_1_readen.xdata)
        self.xport.Add("boreChildrenBd_bore_1_addr_rd", self.boreChildrenBd_bore_1_addr_rd.xdata)
        self.xport.Add("boreChildrenBd_bore_1_outdata", self.boreChildrenBd_bore_1_outdata.xdata)
        self.xport.Add("boreChildrenBd_bore_2_array", self.boreChildrenBd_bore_2_array.xdata)
        self.xport.Add("boreChildrenBd_bore_2_all", self.boreChildrenBd_bore_2_all.xdata)
        self.xport.Add("boreChildrenBd_bore_2_req", self.boreChildrenBd_bore_2_req.xdata)
        self.xport.Add("boreChildrenBd_bore_2_ack", self.boreChildrenBd_bore_2_ack.xdata)
        self.xport.Add("boreChildrenBd_bore_2_writeen", self.boreChildrenBd_bore_2_writeen.xdata)
        self.xport.Add("boreChildrenBd_bore_2_be", self.boreChildrenBd_bore_2_be.xdata)
        self.xport.Add("boreChildrenBd_bore_2_addr", self.boreChildrenBd_bore_2_addr.xdata)
        self.xport.Add("boreChildrenBd_bore_2_indata", self.boreChildrenBd_bore_2_indata.xdata)
        self.xport.Add("boreChildrenBd_bore_2_readen", self.boreChildrenBd_bore_2_readen.xdata)
        self.xport.Add("boreChildrenBd_bore_2_addr_rd", self.boreChildrenBd_bore_2_addr_rd.xdata)
        self.xport.Add("boreChildrenBd_bore_2_outdata", self.boreChildrenBd_bore_2_outdata.xdata)
        self.xport.Add("boreChildrenBd_bore_3_array", self.boreChildrenBd_bore_3_array.xdata)
        self.xport.Add("boreChildrenBd_bore_3_all", self.boreChildrenBd_bore_3_all.xdata)
        self.xport.Add("boreChildrenBd_bore_3_req", self.boreChildrenBd_bore_3_req.xdata)
        self.xport.Add("boreChildrenBd_bore_3_ack", self.boreChildrenBd_bore_3_ack.xdata)
        self.xport.Add("boreChildrenBd_bore_3_writeen", self.boreChildrenBd_bore_3_writeen.xdata)
        self.xport.Add("boreChildrenBd_bore_3_be", self.boreChildrenBd_bore_3_be.xdata)
        self.xport.Add("boreChildrenBd_bore_3_addr", self.boreChildrenBd_bore_3_addr.xdata)
        self.xport.Add("boreChildrenBd_bore_3_indata", self.boreChildrenBd_bore_3_indata.xdata)
        self.xport.Add("boreChildrenBd_bore_3_readen", self.boreChildrenBd_bore_3_readen.xdata)
        self.xport.Add("boreChildrenBd_bore_3_addr_rd", self.boreChildrenBd_bore_3_addr_rd.xdata)
        self.xport.Add("boreChildrenBd_bore_3_outdata", self.boreChildrenBd_bore_3_outdata.xdata)
        self.xport.Add("boreChildrenBd_bore_4_array", self.boreChildrenBd_bore_4_array.xdata)
        self.xport.Add("boreChildrenBd_bore_4_all", self.boreChildrenBd_bore_4_all.xdata)
        self.xport.Add("boreChildrenBd_bore_4_req", self.boreChildrenBd_bore_4_req.xdata)
        self.xport.Add("boreChildrenBd_bore_4_ack", self.boreChildrenBd_bore_4_ack.xdata)
        self.xport.Add("boreChildrenBd_bore_4_writeen", self.boreChildrenBd_bore_4_writeen.xdata)
        self.xport.Add("boreChildrenBd_bore_4_be", self.boreChildrenBd_bore_4_be.xdata)
        self.xport.Add("boreChildrenBd_bore_4_addr", self.boreChildrenBd_bore_4_addr.xdata)
        self.xport.Add("boreChildrenBd_bore_4_indata", self.boreChildrenBd_bore_4_indata.xdata)
        self.xport.Add("boreChildrenBd_bore_4_readen", self.boreChildrenBd_bore_4_readen.xdata)
        self.xport.Add("boreChildrenBd_bore_4_addr_rd", self.boreChildrenBd_bore_4_addr_rd.xdata)
        self.xport.Add("boreChildrenBd_bore_4_outdata", self.boreChildrenBd_bore_4_outdata.xdata)
        self.xport.Add("ICache__metaArray_io_read_ready", self.ICache__metaArray_io_read_ready.xdata)


        # Cascaded ports
        self.auto = self.xport.NewSubPort("auto_")
        self.auto_client_out = self.xport.NewSubPort("auto_client_out_")
        self.auto_client_out_a = self.xport.NewSubPort("auto_client_out_a_")
        self.auto_client_out_a_bits = self.xport.NewSubPort("auto_client_out_a_bits_")
        self.auto_client_out_d = self.xport.NewSubPort("auto_client_out_d_")
        self.auto_client_out_d_bits = self.xport.NewSubPort("auto_client_out_d_bits_")
        self.auto_ctrlUnitOpt_in = self.xport.NewSubPort("auto_ctrlUnitOpt_in_")
        self.auto_ctrlUnitOpt_in_a = self.xport.NewSubPort("auto_ctrlUnitOpt_in_a_")
        self.auto_ctrlUnitOpt_in_a_bits = self.xport.NewSubPort("auto_ctrlUnitOpt_in_a_bits_")
        self.auto_ctrlUnitOpt_in_d = self.xport.NewSubPort("auto_ctrlUnitOpt_in_d_")
        self.auto_ctrlUnitOpt_in_d_bits = self.xport.NewSubPort("auto_ctrlUnitOpt_in_d_bits_")
        self.boreChildrenBd_bore = self.xport.NewSubPort("boreChildrenBd_bore_")
        self.boreChildrenBd_bore_1 = self.xport.NewSubPort("boreChildrenBd_bore_1_")
        self.boreChildrenBd_bore_2 = self.xport.NewSubPort("boreChildrenBd_bore_2_")
        self.boreChildrenBd_bore_3 = self.xport.NewSubPort("boreChildrenBd_bore_3_")
        self.boreChildrenBd_bore_4 = self.xport.NewSubPort("boreChildrenBd_bore_4_")
        self.io = self.xport.NewSubPort("io_")
        self.io_error = self.xport.NewSubPort("io_error_")
        self.io_error_bits = self.xport.NewSubPort("io_error_bits_")
        self.io_fetch = self.xport.NewSubPort("io_fetch_")
        self.io_fetch_req = self.xport.NewSubPort("io_fetch_req_")
        self.io_fetch_req_bits = self.xport.NewSubPort("io_fetch_req_bits_")
        self.io_fetch_req_bits_pcMemRead = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_")
        self.io_fetch_req_bits_pcMemRead_0 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_0_")
        self.io_fetch_req_bits_pcMemRead_1 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_1_")
        self.io_fetch_req_bits_pcMemRead_2 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_2_")
        self.io_fetch_req_bits_pcMemRead_3 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_3_")
        self.io_fetch_req_bits_pcMemRead_4 = self.xport.NewSubPort("io_fetch_req_bits_pcMemRead_4_")
        self.io_fetch_req_bits_readValid = self.xport.NewSubPort("io_fetch_req_bits_readValid_")
        self.io_fetch_resp = self.xport.NewSubPort("io_fetch_resp_")
        self.io_fetch_resp_bits = self.xport.NewSubPort("io_fetch_resp_bits_")
        self.io_fetch_resp_bits_exception = self.xport.NewSubPort("io_fetch_resp_bits_exception_")
        self.io_fetch_resp_bits_itlb_pbmt = self.xport.NewSubPort("io_fetch_resp_bits_itlb_pbmt_")
        self.io_fetch_resp_bits_paddr = self.xport.NewSubPort("io_fetch_resp_bits_paddr_")
        self.io_fetch_resp_bits_pmp_mmio = self.xport.NewSubPort("io_fetch_resp_bits_pmp_mmio_")
        self.io_fetch_resp_bits_vaddr = self.xport.NewSubPort("io_fetch_resp_bits_vaddr_")
        self.io_ftqPrefetch = self.xport.NewSubPort("io_ftqPrefetch_")
        self.io_ftqPrefetch_flushFromBpu = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_")
        self.io_ftqPrefetch_flushFromBpu_s2 = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s2_")
        self.io_ftqPrefetch_flushFromBpu_s2_bits = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s2_bits_")
        self.io_ftqPrefetch_flushFromBpu_s3 = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s3_")
        self.io_ftqPrefetch_flushFromBpu_s3_bits = self.xport.NewSubPort("io_ftqPrefetch_flushFromBpu_s3_bits_")
        self.io_ftqPrefetch_req = self.xport.NewSubPort("io_ftqPrefetch_req_")
        self.io_ftqPrefetch_req_bits = self.xport.NewSubPort("io_ftqPrefetch_req_bits_")
        self.io_ftqPrefetch_req_bits_ftqIdx = self.xport.NewSubPort("io_ftqPrefetch_req_bits_ftqIdx_")
        self.io_itlb = self.xport.NewSubPort("io_itlb_")
        self.io_itlb_0 = self.xport.NewSubPort("io_itlb_0_")
        self.io_itlb_0_req = self.xport.NewSubPort("io_itlb_0_req_")
        self.io_itlb_0_resp_bits = self.xport.NewSubPort("io_itlb_0_resp_bits_")
        self.io_itlb_0_resp_bits_excp = self.xport.NewSubPort("io_itlb_0_resp_bits_excp_")
        self.io_itlb_0_resp_bits_excp_0 = self.xport.NewSubPort("io_itlb_0_resp_bits_excp_0_")
        self.io_itlb_0_resp_bits_gpaddr = self.xport.NewSubPort("io_itlb_0_resp_bits_gpaddr_")
        self.io_itlb_0_resp_bits_paddr = self.xport.NewSubPort("io_itlb_0_resp_bits_paddr_")
        self.io_itlb_0_resp_bits_pbmt = self.xport.NewSubPort("io_itlb_0_resp_bits_pbmt_")
        self.io_itlb_1 = self.xport.NewSubPort("io_itlb_1_")
        self.io_itlb_1_req = self.xport.NewSubPort("io_itlb_1_req_")
        self.io_itlb_1_resp_bits = self.xport.NewSubPort("io_itlb_1_resp_bits_")
        self.io_itlb_1_resp_bits_excp = self.xport.NewSubPort("io_itlb_1_resp_bits_excp_")
        self.io_itlb_1_resp_bits_excp_0 = self.xport.NewSubPort("io_itlb_1_resp_bits_excp_0_")
        self.io_itlb_1_resp_bits_gpaddr = self.xport.NewSubPort("io_itlb_1_resp_bits_gpaddr_")
        self.io_itlb_1_resp_bits_paddr = self.xport.NewSubPort("io_itlb_1_resp_bits_paddr_")
        self.io_itlb_1_resp_bits_pbmt = self.xport.NewSubPort("io_itlb_1_resp_bits_pbmt_")
        self.io_perfInfo = self.xport.NewSubPort("io_perfInfo_")
        self.io_perfInfo_bank_hit = self.xport.NewSubPort("io_perfInfo_bank_hit_")
        self.io_perfInfo_except = self.xport.NewSubPort("io_perfInfo_except_")
        self.io_perfInfo_miss = self.xport.NewSubPort("io_perfInfo_miss_")
        self.io_perfInfo_miss_0 = self.xport.NewSubPort("io_perfInfo_miss_0_")
        self.io_perfInfo_miss_0_except = self.xport.NewSubPort("io_perfInfo_miss_0_except_")
        self.io_perfInfo_miss_0_hit = self.xport.NewSubPort("io_perfInfo_miss_0_hit_")
        self.io_perfInfo_miss_0_miss = self.xport.NewSubPort("io_perfInfo_miss_0_miss_")
        self.io_perfInfo_only = self.xport.NewSubPort("io_perfInfo_only_")
        self.io_perfInfo_only_0 = self.xport.NewSubPort("io_perfInfo_only_0_")
        self.io_pmp = self.xport.NewSubPort("io_pmp_")
        self.io_pmp_0 = self.xport.NewSubPort("io_pmp_0_")
        self.io_pmp_0_resp = self.xport.NewSubPort("io_pmp_0_resp_")
        self.io_pmp_1 = self.xport.NewSubPort("io_pmp_1_")
        self.io_pmp_1_resp = self.xport.NewSubPort("io_pmp_1_resp_")
        self.io_pmp_2 = self.xport.NewSubPort("io_pmp_2_")
        self.io_pmp_2_resp = self.xport.NewSubPort("io_pmp_2_resp_")
        self.io_pmp_3 = self.xport.NewSubPort("io_pmp_3_")
        self.io_pmp_3_resp = self.xport.NewSubPort("io_pmp_3_resp_")
        self.io_softPrefetch = self.xport.NewSubPort("io_softPrefetch_")
        self.io_softPrefetch_0 = self.xport.NewSubPort("io_softPrefetch_0_")
        self.io_softPrefetch_1 = self.xport.NewSubPort("io_softPrefetch_1_")
        self.io_softPrefetch_2 = self.xport.NewSubPort("io_softPrefetch_2_")


    def __del__(self):
        self.Finish()

    ################################
    #         User APIs            #
    ################################
    def InitClock(self, name: str):
        self.xclock.Add(self.xport[name])

    def Step(self, i:int = 1):
        self.xclock.Step(i)

    def StepRis(self, callback, args=(), kwargs={}):
        self.xclock.StepRis(callback, args, kwargs)

    def StepFal(self, callback, args=(), kwargs={}):
        self.xclock.StepFal(callback, args, kwargs)

    def OpenWaveform(self):
        return self.dut.OpenWaveform()

    def CloseWaveform(self):
        return self.dut.CloseWaveform()

    def GetXPort(self):
        return self.xport

    def GetXClock(self):
        return self.xclock

    def SetWaveform(self, filename: str):
        self.dut.SetWaveform(filename)
    
    def FlushWaveform(self):
        self.dut.FlushWaveform()

    def SetCoverage(self, filename: str):
        self.dut.SetCoverage(filename)
    
    def CheckPoint(self, name: str) -> int:
        self.dut.CheckPoint(name)

    def Restore(self, name: str) -> int:
        self.dut.Restore(name)

    def GetInternalSignal(self, name: str, index=-1, is_array=False, use_vpi=False):
        if name not in self.internal_signals:
            signal = None
            if self.dut.GetXSignalCFGBasePtr() != 0 and not use_vpi:
                xname = "CFG:" + name
                if is_array:
                    assert index < 0, "Index is not supported for array signal"
                    signal = self.xcfg.NewXDataArray(name, xname)
                elif index >= 0:
                    signal = self.xcfg.NewXData(name, index, xname)
                else:
                    signal = self.xcfg.NewXData(name, xname)
            else:
                assert index < 0, "Index is not supported for VPI signal"
                assert not is_array, "Array is not supported for VPI signal"
                signal = xsp.XData.FromVPI(self.dut.GetVPIHandleObj(name),
                                           self.dut.GetVPIFuncPtr("vpi_get"),
                                           self.dut.GetVPIFuncPtr("vpi_get_value"),
                                           self.dut.GetVPIFuncPtr("vpi_put_value"), "VPI:" + name)
                if use_vpi:
                    assert signal is not None, f"Internal signal {name} not found (Check VPI is enabled)"
            if signal is None:
                return None
            if not isinstance(signal, xsp.XData):
                self.internal_signals[name] = [xsp.XPin(s, self.event) for s in signal]
            else:
                self.internal_signals[name] = xsp.XPin(signal, self.event)
        return self.internal_signals[name]

    def GetInternalSignalList(self, prefix="", deep=99, use_vpi=False):
        if self.dut.GetXSignalCFGBasePtr() != 0 and not use_vpi:
            return self.xcfg.GetSignalNames(prefix)
        else:
            return self.dut.VPIInternalSignalList(prefix, deep)

    def VPIInternalSignalList(self, prefix="", deep=99):
        return self.dut.VPIInternalSignalList(prefix, deep)

    def Finish(self):
        self.dut.Finish()

    def RefreshComb(self):
        self.dut.RefreshComb()

    ################################
    #      End of User APIs        #
    ################################

    def __getitem__(self, key):
        return xsp.XPin(self.port[key], self.event)

    # Async APIs wrapped from XClock
    async def AStep(self,i: int):
        return await self.xclock.AStep(i)

    async def ACondition(self,fc_cheker):
        return await self.xclock.ACondition(fc_cheker)

    def RunStep(self,i: int):
        return self.xclock.RunStep(i)

    def __setattr__(self, name, value):
        assert not isinstance(getattr(self, name, None),
                              (xsp.XPin, xsp.XData)), \
        f"XPin and XData of DUT are read-only, do you mean to set the value of the signal? please use `{name}.value = ` instead."
        return super().__setattr__(name, value)


if __name__=="__main__":
    dut=DUTICache()
    dut.Step(100)
